// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsoT5wcopa4qbX3_uVLubwEEQmaYXM3_s',
    appId: '1:157812576090:web:4cb25c79763a85a508ed63',
    messagingSenderId: '157812576090',
    projectId: 'nomad-lodge-a504e',
    authDomain: 'nomad-lodge-a504e.firebaseapp.com',
    storageBucket: 'nomad-lodge-a504e.appspot.com',
    measurementId: 'G-WZQ0JY1QV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIfaxcc4Lw-VzqSXiaD408Km5k2KheyYM',
    appId: '1:157812576090:android:c8d517cf2f7d162208ed63',
    messagingSenderId: '157812576090',
    projectId: 'nomad-lodge-a504e',
    storageBucket: 'nomad-lodge-a504e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnHVnBzqRcYEF94NJCpI4CVQLxdGybLFQ',
    appId: '1:157812576090:ios:3fdf0d5a493bc08a08ed63',
    messagingSenderId: '157812576090',
    projectId: 'nomad-lodge-a504e',
    storageBucket: 'nomad-lodge-a504e.appspot.com',
    iosClientId: '157812576090-qun4rc54b2dkj697g1o1ohefba0pgrbi.apps.googleusercontent.com',
    iosBundleId: 'com.nomadfalcon.nomadlodge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnHVnBzqRcYEF94NJCpI4CVQLxdGybLFQ',
    appId: '1:157812576090:ios:3fdf0d5a493bc08a08ed63',
    messagingSenderId: '157812576090',
    projectId: 'nomad-lodge-a504e',
    storageBucket: 'nomad-lodge-a504e.appspot.com',
    iosClientId: '157812576090-qun4rc54b2dkj697g1o1ohefba0pgrbi.apps.googleusercontent.com',
    iosBundleId: 'com.nomadfalcon.nomadlodge',
  );
}
